services:
  - type: web
    name: esp32-log-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
